- name: Create directory on /tmp/
  file:
    path: "{{tmp_path}}"
    state: directory
  run_once: true
  #notify: "folder creation"
  
- name: Create remote file's path
  set_fact:
    remote_file_path: "{{tmp_path}}/inventory_collected_on_{{date}}"
  run_once: true

- name: Create file on the remote to store the sql query's output
  file:
    path: "{{remote_file_path}}"
    state: touch
  #notify: "file creation"
 
